"""
SQL Schema Definer Module
Purpose: Define SQL schema with proper PK/FK relationships from initial_schema.json
and metadata generated by the analyzer.

Responsibilities:
1. Load initial_schema.json (ground truth) and metadata_manager.json
2. Parse field structures to identify:
   - Root-level fields (become columns in main table)
   - Nested objects (become separate tables with FK relationships)
   - Arrays of objects (become junction tables with FK relationships)
   - Arrays of primitives (stored as JSON or separate normalized tables)
3. Create SQLAlchemy models
4. Enforce PK/FK constraints
5. Create actual database tables
"""

import json
import os
from typing import Dict, List, Tuple, Any, Optional
from dataclasses import dataclass
from enum import Enum

try:
    from sqlalchemy import (
        create_engine, Column, Integer, String, Float, Boolean, DateTime,
        ForeignKey, JSON, Table, MetaData, UniqueConstraint, CheckConstraint,
        text, inspect
    )
    from sqlalchemy.orm import declarative_base, relationship, Session
except ImportError:
    print("[!] SQLAlchemy not installed. Install with: pip install sqlalchemy")
    raise

from config import DATA_DIR, INITIAL_SCHEMA_FILE, METADATA_MANAGER_FILE, FIELD_METADATA_FILE

# Global SQLAlchemy setup
Base = declarative_base()

class FieldType(Enum):
    STRING = "string"
    INT = "int"
    FLOAT = "float"
    BOOL = "bool"
    DATETIME = "datetime"
    JSON = "json"
    ARRAY = "array"
    OBJECT = "object"

@dataclass
class SQLField:
    """Represents a SQL column """
    name: str
    sql_type: Any
    nullable: bool = True
    unique: bool = False
    primary_key: bool = False
    foreign_key: Optional[str] = None

@dataclass
class SQLTable:
    """Represents a SQL table structure"""
    table_name: str
    fields: List[SQLField]
    primary_keys: List[str]
    foreign_keys: Dict[str, str]  # column_name -> referenced_table.column
    parent_table: Optional[str] = None
    parent_field: Optional[str] = None  # For junction tables


class SchemaAnalyzer:
    """Analyzes metadata to determine table structure"""
    
    def __init__(self):
        self.initial_schema = {}
        self.metadata_manager = {}
        self.field_metadata = {}
        self.table_hierarchy = {}  # parent -> [children]
        
    def load_schemas(self):
        """Load all schema files"""
        if os.path.exists(INITIAL_SCHEMA_FILE):
            with open(INITIAL_SCHEMA_FILE, 'r') as f:
                self.initial_schema = json.load(f)
        
        if os.path.exists(METADATA_MANAGER_FILE):
            with open(METADATA_MANAGER_FILE, 'r') as f:
                data = json.load(f)
                self.metadata_manager = {
                    field['field_name']: field 
                    for field in data.get('fields', [])
                }
        
        if os.path.exists(FIELD_METADATA_FILE):
            with open(FIELD_METADATA_FILE, 'r') as f:
                self.field_metadata = {
                    field['fieldName']: field
                    for field in json.load(f)
                }
    
    def _map_python_type_to_sql(self, python_type: str) -> Any:
        """Map Python type from schema to SQLAlchemy type"""
        type_map = {
            "string": String(255),
            "int": Integer,
            "float": Float,
            "bool": Boolean,
            "datetime": DateTime,
        }
        return type_map.get(python_type, String(255))
    
    def get_root_fields(self) -> Dict[str, Dict]:
        """Extract root-level fields (not nested objects)"""
        root_fields = {}
        for field_name, field_schema in self.initial_schema.items():
            metadata = self.metadata_manager.get(field_name, {})
            
            # Skip if it's a nested object or array at root level
            if metadata.get('is_nested') or metadata.get('is_array'):
                continue
            
            root_fields[field_name] = {
                'schema_type': field_schema if isinstance(field_schema, str) else 'string',
                'metadata': metadata,
                'unique': field_schema.get('unique', False) if isinstance(field_schema, dict) else False,
                'not_null': field_schema.get('not_null', False) if isinstance(field_schema, dict) else False,
            }
        
        return root_fields
    
    def get_nested_objects(self) -> Dict[str, Dict]:
        """Extract nested object fields (becomes separate tables)"""
        nested = {}
        for field_name, metadata in self.metadata_manager.items():
            if metadata.get('is_nested') and not metadata.get('is_array'):
                # This is a nested object (not an array)
                nested[field_name] = {
                    'metadata': metadata,
                    'parent_path': metadata.get('parent_path'),
                    'nesting_depth': metadata.get('nesting_depth', 1),
                }
        return nested
    
    def get_arrays(self) -> Dict[str, Dict]:
        """Extract array fields"""
        arrays = {}
        for field_name, metadata in self.metadata_manager.items():
            if metadata.get('is_array'):
                arrays[field_name] = {
                    'metadata': metadata,
                    'content_type': metadata.get('array_content_type'),  # 'object' or 'primitive'
                    'parent_path': metadata.get('parent_path'),
                }
        return arrays
    
    def build_table_hierarchy(self):
        """Build relationship graph of tables (parent-child)"""
        # All root fields go in main_records table
        self.table_hierarchy['main_records'] = []
        
        # Nested objects become child tables
        nested = self.get_nested_objects()
        for field_name, info in nested.items():
            parent = info['parent_path'] if info['parent_path'] else 'main_records'
            if parent not in self.table_hierarchy:
                self.table_hierarchy[parent] = []
            self.table_hierarchy[parent].append({
                'field_name': field_name,
                'type': 'nested_object',
                'table_name': f"{parent}_{field_name}".replace('.', '_')
            })
        
        # Arrays become junction tables
        arrays = self.get_arrays()
        for field_name, info in arrays.items():
            parent = info['parent_path'] if info['parent_path'] else 'main_records'
            if parent not in self.table_hierarchy:
                self.table_hierarchy[parent] = []
            array_table_name = f"{parent}_{field_name}".replace('.', '_')
            self.table_hierarchy[parent].append({
                'field_name': field_name,
                'type': 'array',
                'content_type': info['content_type'],
                'table_name': array_table_name
            })


class SQLSchemaBuilder:
    """Builds SQLAlchemy models and creates database schema"""
    
    def __init__(self, database_url: str = None):
        if database_url is None:
            db_path = os.path.join(DATA_DIR, "engine.db")
            database_url = f"sqlite:///{db_path}"
        
        self.database_url = database_url
        self.engine = None
        self.metadata = MetaData()
        self.analyzer = SchemaAnalyzer()
        self.tables = {}  # table_name -> SQLTable definition
        self.models = {}  # table_name -> SQLAlchemy model
    
    def analyze_and_build(self):
        """Load schemas, analyze structure, and build models"""
        print("[*] Loading schema files...")
        self.analyzer.load_schemas()
        
        print("[*] Building table hierarchy...")
        self.analyzer.build_table_hierarchy()
        
        print("[*] Creating SQLAlchemy models...")
        self._create_models()
        
        print("[*] Creating database engine...")
        self.engine = create_engine(self.database_url, echo=False)
        
        print("[*] Creating database tables...")
        self._create_tables()
    
    def _create_models(self):
        """Dynamically create SQLAlchemy models"""
        # 1. Create main_records table
        self._create_main_table()
        
        # 2. Create nested object tables
        nested = self.analyzer.get_nested_objects()
        for field_name, info in nested.items():
            self._create_nested_table(field_name, info)
        
        # 3. Create array tables
        arrays = self.analyzer.get_arrays()
        for field_name, info in arrays.items():
            self._create_array_table(field_name, info)
    
    def _create_main_table(self):
        """Create main_records table from root fields"""
        root_fields = self.analyzer.get_root_fields()
        
        attrs = {
            '__tablename__': 'main_records',
            'id': Column(Integer, primary_key=True, autoincrement=True),
        }
        
        for field_name, info in root_fields.items():
            sql_type = self.analyzer._map_python_type_to_sql(info['schema_type'])
            attrs[field_name] = Column(
                sql_type,
                nullable=not info['not_null'],
                unique=info['unique']
            )
        
        MainRecords = type('MainRecords', (Base,), attrs)
        self.models['main_records'] = MainRecords
        self.tables['main_records'] = MainRecords
    
    def _create_nested_table(self, field_name: str, info: Dict):
        """Create a table for a nested object"""
        parent_path = info['parent_path'] or 'main_records'
        table_name = f"{parent_path}_{field_name}".replace('.', '_')
        
        attrs = {
            '__tablename__': table_name,
            'id': Column(Integer, primary_key=True, autoincrement=True),
            f'{parent_path}_id': Column(Integer, ForeignKey(f'{parent_path}.id'), nullable=False),
        }
        
        NestedTable = type(f'{table_name.capitalize()}', (Base,), attrs)
        self.models[table_name] = NestedTable
        self.tables[table_name] = NestedTable
    
    def _create_array_table(self, field_name: str, info: Dict):
        """Create a table for an array (junction table or simple array table)"""
        parent_path = info['parent_path'] or 'main_records'
        table_name = f"{parent_path}_{field_name}".replace('.', '_')
        content_type = info['content_type']
        
        attrs = {
            '__tablename__': table_name,
            'id': Column(Integer, primary_key=True, autoincrement=True),
            f'{parent_path}_id': Column(Integer, ForeignKey(f'{parent_path}.id'), nullable=False),
        }
        
        if content_type == 'primitive':
            # Store primitive values
            attrs['value'] = Column(String(255), nullable=False)
            attrs['value_type'] = Column(String(50), nullable=True)  # int, float, string, bool
            attrs['position'] = Column(Integer, nullable=True)  # Maintain original array order
        else:
            # For objects in arrays, add generic JSON column (can be extended)
            attrs['data'] = Column(JSON, nullable=False)
            attrs['position'] = Column(Integer, nullable=True)
        
        ArrayTable = type(f'{table_name.capitalize()}', (Base,), attrs)
        self.models[table_name] = ArrayTable
        self.tables[table_name] = ArrayTable
    
    def _create_tables(self):
        """Create actual database tables"""
        Base.metadata.create_all(self.engine)
        print(f"[+] Database schema created at: {self.database_url}")
        
        # Print schema summary
        inspector = inspect(self.engine)
        print("\n[INFO] Created tables:")
        for table_name in inspector.get_table_names():
            columns = inspector.get_columns(table_name)
            print(f"  - {table_name}: {[col['name'] for col in columns]}")
    
    def get_session(self):
        """Get SQLAlchemy session for data operations"""
        from sqlalchemy.orm import sessionmaker
        SessionLocal = sessionmaker(bind=self.engine)
        return SessionLocal()
    
    def get_models(self):
        """Return dictionary of all models"""
        return self.models


def run_schema_definition():
    """Main entry point to define SQL schema"""
    print("\n" + "=" * 80)
    print("SQL SCHEMA DEFINER")
    print("=" * 80)
    
    try:
        builder = SQLSchemaBuilder()
        builder.analyze_and_build()
        
        print("\n" + "=" * 80)
        print("[SUCCESS] SQL Schema definition complete!")
        print("=" * 80)
        print(f"\nDatabase URL: {builder.database_url}")
        print(f"Models available: {list(builder.models.keys())}")
        
        return builder
        
    except FileNotFoundError as e:
        print(f"[!] Error: {e}")
        print("[!] Please ensure initial_schema.json, metadata_manager.json exist first.")
        return None
    except Exception as e:
        print(f"[!] Unexpected error: {e}")
        import traceback
        traceback.print_exc()
        return None


if __name__ == "__main__":
    run_schema_definition()
